## 1D CNN Model - Summary Statistics Calculator

In [ ]:
"""
@authors: Maxime Tchibozo, Zijing Wang
@affiliation: NYSPI, Columbia University
@date: Oct 2020 - Mar 2021
@overview: Computing the f1-score and precision/recall statistics automatically. 
@input: Confusion matrices for each LOOCV Fold.
@output: Performance statistics for each LOOCV test subject Fold.
"""

In [2]:
import numpy as np
## rest = 0, neutral = 1, negative = 2

confusion_matrix0 = np.array([[198,0,2],[3,161,36],[12,26,162]])
confusion_matrix1 = np.array([[184,16,0],[9,183,8],[22,33,145]])
confusion_matrix2 = np.array([[180,12,8],[8,176,16],[3,39,158]])
confusion_matrix3 = np.array([[156,7,37],[10,169,21],[14,19,167]])
confusion_matrix4 = np.array([[163,32,5],[19,162,19],[16,61,123]])

confusion_matrix5 = np.array([[192,8,0],[13,165,22],[4,29,167]])
confusion_matrix6 = np.array([[190,6,4],[30,153,17],[9,24,167]])
confusion_matrix7 = np.array([[181,13,6],[10,181,9],[13,28,159]])
confusion_matrix8 = np.array([[183,9,8],[20,152,28],[1,12,187]])
confusion_matrix9 = np.array([[186,4,10],[4,155,41],[2,21,177]])
confusion_matrix10 = np.array([[197,0,3],[13,156,31],[11,20,169]])


confusion_matrixaverage = np.array([[182.7,9.7,7.5],[12.6,164.8,22.5],[9.7,28.4,161.9]])


confusion_matrix_experiment_B = np.array([[250,53],[59,248]])

matrix_list = [confusion_matrix0,confusion_matrix1,confusion_matrix2,confusion_matrix3,confusion_matrix4
              ,confusion_matrix5,confusion_matrix6,confusion_matrix7,confusion_matrix8,confusion_matrix9
              ,confusion_matrix10,confusion_matrixaverage,confusion_matrix_experiment_B]

from sklearn import metrics
def generate_y_pred(matrix_list):  
    
    for x in matrix_list:
        if x !='confusion_matrix_experiment_B':

            n_classes = 3

            y_true = []
            for i in range(n_classes):
                y_true.extend([i]*sum(x[i]))


            #We can then build y_pred by doing:

            y_pred = []
            for i in range(n_classes):
                for j in range(n_classes):
                    y_pred+=[j]*x[i][j]

            print("Validate the y_pred and y_true is correct:")


            # Print the confusion matrix
            print(metrics.confusion_matrix(y_true, y_pred))

            # Print the precision and recall, among other metrics
            print(metrics.classification_report(y_true, y_pred, digits=3))
        else:
            n_classes = 2

            y_true = []
            for i in range(n_classes):
                y_true.extend([i]*sum(x[i]))


            #We can then build y_pred by doing:

            y_pred = []
            for i in range(n_classes):
                for j in range(n_classes):
                    y_pred+=[j]*x[i][j]

            print("Validate the y_pred and y_true is correct:")


            # Print the confusion matrix
            print(metrics.confusion_matrix(y_true, y_pred))

            # Print the precision and recall, among other metrics
            print(metrics.classification_report(y_true, y_pred, digits=3))

    
    return y_true,y_pred

generate_y_pred(matrix_list)

Validate the y_pred and y_true is correct:
[[198   0   2]
 [  3 161  36]
 [ 12  26 162]]
              precision    recall  f1-score   support

           0      0.930     0.990     0.959       200
           1      0.861     0.805     0.832       200
           2      0.810     0.810     0.810       200

    accuracy                          0.868       600
   macro avg      0.867     0.868     0.867       600
weighted avg      0.867     0.868     0.867       600

Validate the y_pred and y_true is correct:
[[184  16   0]
 [  9 183   8]
 [ 22  33 145]]
              precision    recall  f1-score   support

           0      0.856     0.920     0.887       200
           1      0.789     0.915     0.847       200
           2      0.948     0.725     0.822       200

    accuracy                          0.853       600
   macro avg      0.864     0.853     0.852       600
weighted avg      0.864     0.853     0.852       600

Validate the y_pred and y_true is correct:
[[180  12   8]
 [

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


TypeError: ignored

In [3]:
confusion_matrix_experiment_B = np.array([[250,53],[59,248]])

for x in [confusion_matrix_experiment_B]:
        n_classes = 2

        y_true = []
        for i in range(n_classes):
            y_true.extend([i]*sum(x[i]))


        #We can then build y_pred by doing:

        y_pred = []
        for i in range(n_classes):
            for j in range(n_classes):
                y_pred+=[j]*x[i][j]

        print("Validate the y_pred and y_true is correct:")


        # Print the confusion matrix
        print(metrics.confusion_matrix(y_true, y_pred))

        # Print the precision and recall, among other metrics
        print(metrics.classification_report(y_true, y_pred, digits=3))





Validate the y_pred and y_true is correct:
[[250  53]
 [ 59 248]]
              precision    recall  f1-score   support

           0      0.809     0.825     0.817       303
           1      0.824     0.808     0.816       307

    accuracy                          0.816       610
   macro avg      0.816     0.816     0.816       610
weighted avg      0.817     0.816     0.816       610



In [6]:
u = metrics.classification_report(y_true, y_pred, digits=3, output_dict=True)


In [7]:
u

{'0': {'f1-score': 0.8169934640522876,
  'precision': 0.8090614886731392,
  'recall': 0.8250825082508251,
  'support': 303},
 '1': {'f1-score': 0.8157894736842105,
  'precision': 0.8239202657807309,
  'recall': 0.8078175895765473,
  'support': 307},
 'accuracy': 0.8163934426229508,
 'macro avg': {'f1-score': 0.816391468868249,
  'precision': 0.816490877226935,
  'recall': 0.8164500489136861,
  'support': 610},
 'weighted avg': {'f1-score': 0.8163875213588455,
  'precision': 0.8165395945289272,
  'recall': 0.8163934426229508,
  'support': 610}}

In [10]:
def generate_y_pred(matrix_list):  
    output_list = []
    for x in matrix_list:
        if x !='confusion_matrix_experiment_B':

            n_classes = 3

            y_true = []
            for i in range(n_classes):
                y_true.extend([i]*sum(x[i]))


            #We can then build y_pred by doing:

            y_pred = []
            for i in range(n_classes):
                for j in range(n_classes):
                    y_pred+=[j]*x[i][j]

            print("Validate the y_pred and y_true is correct:")


            # Print the confusion matrix
            print(metrics.confusion_matrix(y_true, y_pred))

            # Print the precision and recall, among other metrics
            output_list.append(metrics.classification_report(y_true, y_pred, digits=3,output_dict=True))

    return output_list

output_list = generate_y_pred(matrix_list[:-2])

Validate the y_pred and y_true is correct:
[[198   0   2]
 [  3 161  36]
 [ 12  26 162]]
Validate the y_pred and y_true is correct:
[[184  16   0]
 [  9 183   8]
 [ 22  33 145]]
Validate the y_pred and y_true is correct:
[[180  12   8]
 [  8 176  16]
 [  3  39 158]]
Validate the y_pred and y_true is correct:
[[156   7  37]
 [ 10 169  21]
 [ 14  19 167]]
Validate the y_pred and y_true is correct:
[[163  32   5]
 [ 19 162  19]
 [ 16  61 123]]
Validate the y_pred and y_true is correct:
[[192   8   0]
 [ 13 165  22]
 [  4  29 167]]
Validate the y_pred and y_true is correct:
[[190   6   4]
 [ 30 153  17]
 [  9  24 167]]
Validate the y_pred and y_true is correct:
[[181  13   6]
 [ 10 181   9]
 [ 13  28 159]]
Validate the y_pred and y_true is correct:
[[183   9   8]
 [ 20 152  28]
 [  1  12 187]]
Validate the y_pred and y_true is correct:
[[186   4  10]
 [  4 155  41]
 [  2  21 177]]
Validate the y_pred and y_true is correct:
[[197   0   3]
 [ 13 156  31]
 [ 11  20 169]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  after removing the cwd from sys.path.


In [21]:
len(output_list)

11

In [18]:
print('class 0')
print('precision:',format(np.mean([x['0']['precision'] for x in output_list]),'.3f'))
print('precision std:',format(np.std([x['0']['precision'] for x in output_list]),'.3f'))
print('recall:',format(np.mean([x['0']['recall'] for x in output_list]),'.3f'))
print('recall std:',format(np.std([x['0']['recall'] for x in output_list]),'.3f'))
print('f1-score:',format(np.mean([x['0']['f1-score'] for x in output_list]),'.3f'))
print('f1-score std:',format(np.std([x['0']['f1-score'] for x in output_list]),'.3f'))

class 0
precision: 0.892
precision std: 0.044
recall: 0.914
recall std: 0.062
f1-score: 0.902
f1-score std: 0.045


In [19]:
print('class 1')
print('precision:',format(np.mean([x['1']['precision'] for x in output_list]),'.3f'))
print('precision std:',format(np.std([x['1']['precision'] for x in output_list]),'.3f'))
print('recall:',format(np.mean([x['1']['recall'] for x in output_list]),'.3f'))
print('recall std:',format(np.std([x['1']['recall'] for x in output_list]),'.3f'))
print('f1-score:',format(np.mean([x['1']['f1-score'] for x in output_list]),'.3f'))
print('f1-score std:',format(np.std([x['1']['f1-score'] for x in output_list]),'.3f'))

class 1
precision: 0.820
precision std: 0.068
recall: 0.824
recall std: 0.053
f1-score: 0.819
f1-score std: 0.038


In [20]:
print('class 2')
print('precision:',format(np.mean([x['2']['precision'] for x in output_list]),'.3f'))
print('precision std:',format(np.std([x['2']['precision'] for x in output_list]),'.3f'))
print('recall:',format(np.mean([x['2']['recall'] for x in output_list]),'.3f'))
print('recall std:',format(np.std([x['2']['recall'] for x in output_list]),'.3f'))
print('f1-score:',format(np.mean([x['2']['f1-score'] for x in output_list]),'.3f'))
print('f1-score std:',format(np.std([x['2']['f1-score'] for x in output_list]),'.3f'))

class 2
precision: 0.849
precision std: 0.057
recall: 0.810
recall std: 0.080
f1-score: 0.825
f1-score std: 0.045


In [31]:
def generate_y_pred(matrix_list):  
    output_list = []
    for x in matrix_list:
        n_classes = 2

        y_true = []
        for i in range(n_classes):
            y_true.extend([i]*sum(x[i]))


        #We can then build y_pred by doing:

        y_pred = []
        for i in range(n_classes):
            for j in range(n_classes):
                y_pred+=[j]*x[i][j]

        print("Validate the y_pred and y_true is correct:")


        # Print the confusion matrix
        print(metrics.confusion_matrix(y_true, y_pred))

        # Print the precision and recall, among other metrics
        output_list.append(metrics.classification_report(y_true, y_pred, digits=3,output_dict=True))

    return output_list

output_list = generate_y_pred([matrix_list[-1]])

Validate the y_pred and y_true is correct:
[[250  53]
 [ 59 248]]


In [32]:
output_list

[{'0': {'f1-score': 0.8169934640522876,
   'precision': 0.8090614886731392,
   'recall': 0.8250825082508251,
   'support': 303},
  '1': {'f1-score': 0.8157894736842105,
   'precision': 0.8239202657807309,
   'recall': 0.8078175895765473,
   'support': 307},
  'accuracy': 0.8163934426229508,
  'macro avg': {'f1-score': 0.816391468868249,
   'precision': 0.816490877226935,
   'recall': 0.8164500489136861,
   'support': 610},
  'weighted avg': {'f1-score': 0.8163875213588455,
   'precision': 0.8165395945289272,
   'recall': 0.8163934426229508,
   'support': 610}}]

In [33]:
print('class 0')
print('precision:',format(np.mean([x['0']['precision'] for x in output_list]),'.3f'))
print('precision std:',format(np.std([x['0']['precision'] for x in output_list]),'.3f'))
print('recall:',format(np.mean([x['0']['recall'] for x in output_list]),'.3f'))
print('recall std:',format(np.std([x['0']['recall'] for x in output_list]),'.3f'))
print('f1-score:',format(np.mean([x['0']['f1-score'] for x in output_list]),'.3f'))
print('f1-score std:',format(np.std([x['0']['f1-score'] for x in output_list]),'.3f'))

class 0
precision: 0.809
precision std: 0.000
recall: 0.825
recall std: 0.000
f1-score: 0.817
f1-score std: 0.000


In [34]:
print('class 1')
print('precision:',format(np.mean([x['1']['precision'] for x in output_list]),'.3f'))
print('precision std:',format(np.std([x['1']['precision'] for x in output_list]),'.3f'))
print('recall:',format(np.mean([x['1']['recall'] for x in output_list]),'.3f'))
print('recall std:',format(np.std([x['1']['recall'] for x in output_list]),'.3f'))
print('f1-score:',format(np.mean([x['1']['f1-score'] for x in output_list]),'.3f'))
print('f1-score std:',format(np.std([x['1']['f1-score'] for x in output_list]),'.3f'))

class 1
precision: 0.824
precision std: 0.000
recall: 0.808
recall std: 0.000
f1-score: 0.816
f1-score std: 0.000
